export const SITE = {
  website: "https://blog.ipseforma.com/",
  author: "ipseforma",
  profile: "https://ipseforma.com/",
  desc: "Notes on finding yourself through form and practice.",
  title: "ipseforma",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/zeenoo11/ipseforma-blog/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Seoul",
} as const;
